import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

export const emailTemplates = {
  pricing_alert: {
    name: 'pricing_alert',
    templateType: 'pricing_alert',
    subject: '🚨 {{competitorName}} {{changeType}} - Pricing Update Alert',
    htmlContent: `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pricing Alert</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f8fafc; }
    .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; text-align: center; }
    .content { padding: 30px; }
    .alert-badge { display: inline-block; background-color: #ef4444; color: white; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; margin-bottom: 15px; }
    .competitor-name { color: #1f2937; font-weight: 600; font-size: 18px; }
    .impact-section { background-color: #fef3c7; border-left: 4px solid #f59e0b; padding: 20px; margin: 20px 0; border-radius: 4px; }
    .impact-title { color: #92400e; font-weight: 600; margin: 0 0 10px 0; }
    .change-details { background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .change-item { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e5e7eb; }
    .change-item:last-child { border-bottom: none; }
    .old-value { color: #ef4444; text-decoration: line-through; }
    .new-value { color: #10b981; font-weight: 600; }
    .cta-button { display: inline-block; background-color: #3b82f6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 500; margin: 20px 0; }
    .footer { background-color: #f9fafb; padding: 20px; text-align: center; color: #6b7280; font-size: 14px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1 style="margin: 0; font-size: 24px;">🚨 Competitor Pricing Alert</h1>
    </div>
    
    <div class="content">
      <div class="alert-badge">{{impactLevel}} IMPACT</div>
      
      <p>Hi {{userName}},</p>
      
      <p><strong class="competitor-name">{{competitorName}}</strong> just made a pricing change on their {{pageType}} page.</p>
      
      <div class="impact-section">
        <h3 class="impact-title">COMPETITIVE IMPACT:</h3>
        <p>{{competitiveAnalysis}}</p>
        <ul>
          <li>This affects your market positioning</li>
          <li>Consider reviewing your pricing strategy</li>
          <li>Monitor customer response and inquiries</li>
        </ul>
      </div>
      
      <div class="change-details">
        <h3 style="margin: 0 0 15px 0; color: #374151;">What Changed:</h3>
        <div class="change-item">
          <span><strong>Change Summary:</strong></span>
          <span>{{changeSummary}}</span>
        </div>
        {{#oldValue}}
        <div class="change-item">
          <span><strong>Before:</strong></span>
          <span class="old-value">{{oldValue}}</span>
        </div>
        {{/oldValue}}
        {{#newValue}}
        <div class="change-item">
          <span><strong>After:</strong></span>
          <span class="new-value">{{newValue}}</span>
        </div>
        {{/newValue}}
        <div class="change-item">
          <span><strong>Page Type:</strong></span>
          <span>{{pageType}}</span>
        </div>
        <div class="change-item">
          <span><strong>Detected:</strong></span>
          <span>Just now</span>
        </div>
      </div>
      
      <p>
        <a href="{{viewChangeUrl}}" class="cta-button">View Full Analysis →</a>
      </p>
      
      <p>
        <a href="{{pageUrl}}" style="color: #3b82f6; text-decoration: none;">View competitor page →</a> | 
        <a href="{{dashboardUrl}}" style="color: #3b82f6; text-decoration: none;">Go to Dashboard →</a>
      </p>
    </div>
    
    <div class="footer">
      <p>This alert was generated by your Website Change Alert monitoring system.<br>
      <a href="{{dashboardUrl}}/settings/notifications" style="color: #6b7280;">Manage notification preferences</a></p>
    </div>
  </div>
</body>
</html>
    `,
    textContent: `
🚨 PRICING ALERT: {{competitorName}} {{changeType}}

Hi {{userName}},

{{competitorName}} just made a pricing change on their {{pageType}} page.

COMPETITIVE IMPACT:
{{competitiveAnalysis}}

• This affects your market positioning
• Consider reviewing your pricing strategy  
• Monitor customer response and inquiries

WHAT CHANGED:
• Change Summary: {{changeSummary}}
{{#oldValue}}• Before: {{oldValue}}{{/oldValue}}
{{#newValue}}• After: {{newValue}}{{/newValue}}
• Page Type: {{pageType}}
• Detected: Just now

View full analysis: {{viewChangeUrl}}
View competitor page: {{pageUrl}}
Go to Dashboard: {{dashboardUrl}}

---
This alert was generated by your Website Change Alert monitoring system.
Manage notification preferences: {{dashboardUrl}}/settings/notifications
    `,
    variables: {
      userName: 'User name',
      competitorName: 'Competitor company name',
      changeType: 'Type of change detected',
      changeSummary: 'Brief summary of the change',
      impactLevel: 'high/medium/low',
      oldValue: 'Previous value (optional)',
      newValue: 'New value (optional)', 
      competitiveAnalysis: 'AI-generated competitive analysis',
      pageType: 'pricing/features/blog/homepage',
      pageUrl: 'URL of the changed page',
      viewChangeUrl: 'URL to view change details',
      dashboardUrl: 'URL to user dashboard'
    }
  },

  feature_alert: {
    name: 'feature_alert',
    templateType: 'feature_alert',
    subject: '📢 {{competitorName}} launched new feature: {{changeSummary}}',
    htmlContent: `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Feature Alert</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f8fafc; }
    .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }
    .header { background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 20px; text-align: center; }
    .content { padding: 30px; }
    .alert-badge { display: inline-block; background-color: #10b981; color: white; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; margin-bottom: 15px; }
    .competitor-name { color: #1f2937; font-weight: 600; font-size: 18px; }
    .impact-section { background-color: #ecfdf5; border-left: 4px solid #10b981; padding: 20px; margin: 20px 0; border-radius: 4px; }
    .impact-title { color: #047857; font-weight: 600; margin: 0 0 10px 0; }
    .feature-details { background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .feature-item { padding: 8px 0; border-bottom: 1px solid #e5e7eb; }
    .feature-item:last-child { border-bottom: none; }
    .feature-item strong { color: #374151; }
    .new-feature { color: #10b981; font-weight: 600; }
    .cta-button { display: inline-block; background-color: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 500; margin: 20px 0; }
    .footer { background-color: #f9fafb; padding: 20px; text-align: center; color: #6b7280; font-size: 14px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1 style="margin: 0; font-size: 24px;">📢 New Feature Alert</h1>
    </div>
    
    <div class="content">
      <div class="alert-badge">FEATURE UPDATE</div>
      
      <p>Hi {{userName}},</p>
      
      <p><strong class="competitor-name">{{competitorName}}</strong> just announced a new feature on their {{pageType}} page.</p>
      
      <div class="impact-section">
        <h3 class="impact-title">COMPETITIVE IMPACT:</h3>
        <p>{{competitiveAnalysis}}</p>
        <ul>
          <li>This may address a gap in your current offering</li>
          <li>Consider feature gap analysis for your roadmap</li>
          <li>Monitor market reception and customer feedback</li>
        </ul>
      </div>
      
      <div class="feature-details">
        <h3 style="margin: 0 0 15px 0; color: #374151;">What's New:</h3>
        <div class="feature-item">
          <strong>Feature Summary:</strong><br>
          <span class="new-feature">{{changeSummary}}</span>
        </div>
        {{#newValue}}
        <div class="feature-item">
          <strong>Details:</strong><br>
          {{newValue}}
        </div>
        {{/newValue}}
        <div class="feature-item">
          <strong>Page Type:</strong> {{pageType}}
        </div>
        <div class="feature-item">
          <strong>Impact Level:</strong> {{impactLevel}}
        </div>
        <div class="feature-item">
          <strong>Detected:</strong> Just now
        </div>
      </div>
      
      <p>
        <a href="{{viewChangeUrl}}" class="cta-button">View Full Analysis →</a>
      </p>
      
      <p>
        <a href="{{pageUrl}}" style="color: #10b981; text-decoration: none;">View competitor page →</a> | 
        <a href="{{dashboardUrl}}" style="color: #10b981; text-decoration: none;">Add to roadmap review →</a>
      </p>
    </div>
    
    <div class="footer">
      <p>This alert was generated by your Website Change Alert monitoring system.<br>
      <a href="{{dashboardUrl}}/settings/notifications" style="color: #6b7280;">Manage notification preferences</a></p>
    </div>
  </div>
</body>
</html>
    `,
    textContent: `
📢 FEATURE ALERT: {{competitorName}} launched new feature

Hi {{userName}},

{{competitorName}} just announced a new feature on their {{pageType}} page.

COMPETITIVE IMPACT:
{{competitiveAnalysis}}

• This may address a gap in your current offering
• Consider feature gap analysis for your roadmap
• Monitor market reception and customer feedback

WHAT'S NEW:
• Feature Summary: {{changeSummary}}
{{#newValue}}• Details: {{newValue}}{{/newValue}}
• Page Type: {{pageType}}
• Impact Level: {{impactLevel}}
• Detected: Just now

View full analysis: {{viewChangeUrl}}
View competitor page: {{pageUrl}}
Add to roadmap review: {{dashboardUrl}}

---
This alert was generated by your Website Change Alert monitoring system.
Manage notification preferences: {{dashboardUrl}}/settings/notifications
    `,
    variables: {
      userName: 'User name',
      competitorName: 'Competitor company name',
      changeSummary: 'Brief summary of the new feature',
      impactLevel: 'high/medium/low',
      newValue: 'Details about the new feature (optional)',
      competitiveAnalysis: 'AI-generated competitive analysis',
      pageType: 'features/product/blog/homepage',
      pageUrl: 'URL of the changed page',
      viewChangeUrl: 'URL to view change details',
      dashboardUrl: 'URL to user dashboard'
    }
  },

  weekly_summary: {
    name: 'weekly_summary',
    templateType: 'weekly_summary',
    subject: '📊 Weekly Competitor Activity Summary - {{competitorCount}} companies monitored',
    htmlContent: `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Weekly Summary</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f8fafc; }
    .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }
    .header { background: linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%); color: white; padding: 20px; text-align: center; }
    .content { padding: 30px; }
    .summary-stats { display: flex; justify-content: space-between; margin: 20px 0; }
    .stat-item { text-align: center; flex: 1; padding: 15px; background-color: #f8fafc; margin: 0 5px; border-radius: 8px; }
    .stat-number { font-size: 24px; font-weight: 600; color: #8b5cf6; }
    .stat-label { font-size: 12px; color: #6b7280; text-transform: uppercase; }
    .section { margin: 30px 0; }
    .section-title { color: #374151; font-weight: 600; margin: 0 0 15px 0; padding-bottom: 5px; border-bottom: 2px solid #e5e7eb; }
    .change-item { background-color: #f9fafb; padding: 15px; margin: 10px 0; border-radius: 6px; border-left: 4px solid #8b5cf6; }
    .change-header { display: flex; justify-content: between; align-items: center; margin-bottom: 5px; }
    .competitor-name { font-weight: 600; color: #1f2937; }
    .impact-badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 500; }
    .impact-high { background-color: #fee2e2; color: #991b1b; }
    .impact-medium { background-color: #fef3c7; color: #92400e; }
    .impact-low { background-color: #ecfdf5; color: #047857; }
    .change-summary { color: #4b5563; margin: 5px 0; }
    .cta-button { display: inline-block; background-color: #8b5cf6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 500; margin: 20px 10px 20px 0; }
    .footer { background-color: #f9fafb; padding: 20px; text-align: center; color: #6b7280; font-size: 14px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1 style="margin: 0; font-size: 24px;">📊 Weekly Competitor Summary</h1>
      <p style="margin: 5px 0 0 0; opacity: 0.9;">{{weekRange}}</p>
    </div>
    
    <div class="content">
      <p>Hi {{userName}},</p>
      
      <p>Here's your weekly competitive intelligence summary for the companies you're monitoring.</p>
      
      <div class="summary-stats">
        <div class="stat-item">
          <div class="stat-number">{{totalChanges}}</div>
          <div class="stat-label">Total Changes</div>
        </div>
        <div class="stat-item">
          <div class="stat-number">{{competitorCount}}</div>
          <div class="stat-label">Companies</div>
        </div>
        <div class="stat-item">
          <div class="stat-number">{{highImpactChanges}}</div>
          <div class="stat-label">High Impact</div>
        </div>
      </div>
      
      {{#pricingChanges}}
      <div class="section">
        <h3 class="section-title">💰 Pricing Changes</h3>
        {{#changes}}
        <div class="change-item">
          <div class="change-header">
            <span class="competitor-name">{{competitorName}}</span>
            <span class="impact-badge impact-{{impactLevel}}">{{impactLevel}} impact</span>
          </div>
          <div class="change-summary">{{changeSummary}}</div>
        </div>
        {{/changes}}
      </div>
      {{/pricingChanges}}
      
      {{#featureChanges}}
      <div class="section">
        <h3 class="section-title">🚀 New Features & Updates</h3>
        {{#changes}}
        <div class="change-item">
          <div class="change-header">
            <span class="competitor-name">{{competitorName}}</span>
            <span class="impact-badge impact-{{impactLevel}}">{{impactLevel}} impact</span>
          </div>
          <div class="change-summary">{{changeSummary}}</div>
        </div>
        {{/changes}}
      </div>
      {{/featureChanges}}
      
      {{#messagingChanges}}
      <div class="section">
        <h3 class="section-title">📝 Messaging & Positioning</h3>
        {{#changes}}
        <div class="change-item">
          <div class="change-header">
            <span class="competitor-name">{{competitorName}}</span>
            <span class="impact-badge impact-{{impactLevel}}">{{impactLevel}} impact</span>
          </div>
          <div class="change-summary">{{changeSummary}}</div>
        </div>
        {{/changes}}
      </div>
      {{/messagingChanges}}
      
      <div class="section">
        <h3 class="section-title">🎯 Recommended Actions</h3>
        <ul>
          <li>Review pricing strategy against recent competitor changes</li>
          <li>Analyze feature gaps and prioritize roadmap items</li>
          <li>Update competitive positioning based on messaging changes</li>
          <li>Monitor customer feedback and market response</li>
        </ul>
      </div>
      
      <p>
        <a href="{{dashboardUrl}}" class="cta-button">View Full Dashboard →</a>
        <a href="{{viewAllChangesUrl}}" class="cta-button">View All Changes →</a>
      </p>
    </div>
    
    <div class="footer">
      <p>This summary was generated by your Website Change Alert monitoring system.<br>
      <a href="{{dashboardUrl}}/settings/notifications" style="color: #6b7280;">Manage notification preferences</a></p>
    </div>
  </div>
</body>
</html>
    `,
    textContent: `
📊 WEEKLY COMPETITOR SUMMARY
{{weekRange}}

Hi {{userName}},

Here's your weekly competitive intelligence summary:

SUMMARY STATS:
• Total Changes: {{totalChanges}}
• Companies Monitored: {{competitorCount}}
• High Impact Changes: {{highImpactChanges}}

{{#pricingChanges}}
💰 PRICING CHANGES:
{{#changes}}
• {{competitorName}}: {{changeSummary}} ({{impactLevel}} impact)
{{/changes}}

{{/pricingChanges}}
{{#featureChanges}}
🚀 NEW FEATURES & UPDATES:
{{#changes}}
• {{competitorName}}: {{changeSummary}} ({{impactLevel}} impact)
{{/changes}}

{{/featureChanges}}
{{#messagingChanges}}
📝 MESSAGING & POSITIONING:
{{#changes}}
• {{competitorName}}: {{changeSummary}} ({{impactLevel}} impact)
{{/changes}}

{{/messagingChanges}}
🎯 RECOMMENDED ACTIONS:
• Review pricing strategy against recent competitor changes
• Analyze feature gaps and prioritize roadmap items  
• Update competitive positioning based on messaging changes
• Monitor customer feedback and market response

View Full Dashboard: {{dashboardUrl}}
View All Changes: {{viewAllChangesUrl}}

---
This summary was generated by your Website Change Alert monitoring system.
Manage notification preferences: {{dashboardUrl}}/settings/notifications
    `,
    variables: {
      userName: 'User name',
      weekRange: 'Date range for the week',
      totalChanges: 'Total number of changes detected',
      competitorCount: 'Number of competitors monitored',
      highImpactChanges: 'Number of high impact changes',
      pricingChanges: 'Array of pricing changes',
      featureChanges: 'Array of feature changes',
      messagingChanges: 'Array of messaging changes',
      dashboardUrl: 'URL to user dashboard',
      viewAllChangesUrl: 'URL to view all changes'
    }
  }
}

export async function seedEmailTemplates() {
  console.log('Seeding email templates...')
  
  for (const template of Object.values(emailTemplates)) {
    await db.emailTemplate.upsert({
      where: { name: template.name },
      update: {
        templateType: template.templateType,
        subject: template.subject,
        htmlContent: template.htmlContent,
        textContent: template.textContent,
        variables: template.variables,
        isActive: true
      },
      create: {
        name: template.name,
        templateType: template.templateType,
        subject: template.subject,
        htmlContent: template.htmlContent,
        textContent: template.textContent,
        variables: template.variables,
        isActive: true
      }
    })
  }
  
  console.log('Email templates seeded successfully!')
}

export async function getTemplate(templateType: 'pricing_alert' | 'feature_alert' | 'weekly_summary') {
  return await db.emailTemplate.findFirst({
    where: { 
      templateType,
      isActive: true 
    }
  })
}